In [2]:
import numpy as np

In [3]:
arr = np.array([10 , 20 , 30 , 40])
print(arr)

[10 20 30 40]


In [5]:
arr = np.array([[1 , 2 , 3 ,4],
               [5 , 6 ,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr = np.array([10 , 20 , 30.12 , 40])
arr.dtype

dtype('float64')

In [16]:
print(np.zeros((2 ,4)))
print("")
print(np.zeros(4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0. 0. 0. 0.]


In [14]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
print(np.ones(5))
print("")
print(np.ones((5 ,5)))

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
print(np.arange(2 , 21 , 1))
print(np.arange(2 , 21)) 
print(np.arange(2 , 21 , 2))
print(np.arange(1 ,51 , 2))

[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.
 20.]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [27]:
np.linspace(1 , 10 , 4)

array([ 1.,  4.,  7., 10.])

In [ ]:
arr = np.array([10 , 20 , 30 , 40])
arr.dtype
## astype convert it in other type forcefully

dtype('int64')

In [ ]:
arr = np.arange(1 , 21 , 2)
r=arr.astype(float) ## return the value in the new variable , not change the orginal arrays data type
r.dtype

dtype('float64')

In [35]:
m = np.array([[1, 2, 3],
[4, 5, 6]])
print(m.shape) ## give the row and columb
print(m.ndim)
print(m.size) ## give the number of element in the arrays 
print(m.dtype)

(2, 3)
2
6
int64


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20])

In [43]:
arr = np.array([[1 , 2 , 3 ,4],
                 [5 , 6 ,7,8]])

## arr[row , coloumb]
arr[0:2 , 2:4]



array([[3, 4],
       [7, 8]])

In [50]:
marks = np.array([45, 82, 67, 33, 91])

marks[(marks!=45) & (marks>10)]


array([82, 67, 33, 91])

In [55]:
arr = np.array([10, 20, 30, 40, 50])

x = arr[1:4]
print(x)
x[0] = 999
print(x)
print(arr)



[20 30 40]
[999  30  40]
[ 10 999  30  40  50]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

x = arr[1:4].copy()
print(x)
x[0] = 999
print(x)
print(arr)



[20 30 40]
[999  30  40]
[10 20 30 40 50]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr1 = arr+5
print(arr+arr1)
print(arr-arr1)
print(arr*arr1)
print(arr/arr1)



[ 25  45  65  85 105]
[-5 -5 -5 -5 -5]
[ 150  500 1050 1800 2750]
[0.66666667 0.8        0.85714286 0.88888889 0.90909091]


In [ ]:
arr = np.array([[1 , 2 , 3 ,4],
                 [5 , 6 ,7,8],
                 [9, 3 , 2 , 1]])

arr1 = np.array([[11, 12 ,13 ,14],
                 [15 ,16, 17 ,18],
                 [19 ,13 ,12, 11]])

print(arr*arr1)
print(arr.shape)
print(arr1.shape)

[[ 11  24  39  56]
 [ 75  96 119 144]
 [171  39  24  11]]
(3, 4)
(3, 4)


In [80]:
arr = np.array([10, 20, 30, 40, 50])
arr.sum()
arr.mean()
arr.std()
arr.var()

np.median(arr)
print(arr.argmax())
print(arr.argmin())

4
0


In [83]:
arr = np.array([[11, 12 ,13 ,14],
                 [15 ,16, 17 ,18],
                 [19 ,13 ,12, 11]])
arr.sum(axis=1)

array([50, 66, 55])

In [85]:
### question 
arr = np.arange(1 , 13 , 2)
print(arr)

[ 1  3  5  7  9 11]


In [86]:
arr = np.linspace(5 ,45 , 9)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [ ]:
arr = np.arange(1 , 10) ## give the int value 
arr1 = np.linspace(1, 9 , 9) ## give the floate value 
print(arr.dtype)
print(arr1.dtype)

int64
float64


In [ ]:
arr = np.eye(6)
print(arr.dtype)
arr1 = arr.astype(int)
print(arr1)

float64
[[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
arr= np.full((3, 4) , 5)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(3, 4)
12
2


In [96]:
np.array([10.23, 13.45, 30.54, 56.21]).astype(int)

array([10, 13, 30, 56])

In [99]:
arr = np.arange(10 , 101 , 10)
print(arr)
print(arr[3])
print(arr[-1])
print(arr[-2])
print(arr[2:6])
arr1 = arr[::-1]
print(arr1)

[ 10  20  30  40  50  60  70  80  90 100]
40
100
90
[30 40 50 60]
[100  90  80  70  60  50  40  30  20  10]


In [101]:
arr = np.arange(1 ,21)
print(arr)
print(arr[2:18])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [125]:
m = np.array([[ 1, 2, 3, 4, 5],
              [ 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
print(m[1:4 , 1:4])
# print(m[2])
# print(m[:,-1])


print(m[0:5:4,0:5:4])
a = m[:, -1][0]
b = m[:, -1][-1]
c = m[:,0][0]
d = m[:,0][-1]
s = [[c , a],[d , b]]
# print(a , b, c ,d)
print("")
print(m[::2, ::2])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 1  5]
 [21 25]]

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [137]:
m = np.array([[ 1, 2, 3, 4, 5],
              [ 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
f = m.flatten()
r = m.ravel()


f[0] = 999
print(m)
r[0] = 999
print(m)






[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[999   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]


In [142]:
## sheet nuner 2


marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])
arr = np.array([5 , 2 , 8])
arr1 = marks + arr
print(arr1)

np.where(arr1>100 , 100, marks)

[[ 93  98 103]
 [ 77 101  99]
 [103  87 105]
 [ 65  77  88]]


array([[ 88,  96, 100],
       [ 72, 100,  91],
       [100,  85, 100],
       [ 60,  75,  80]])

In [151]:
arr = np.ones((5 ,5))

arr[1:4, 1:4] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [152]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [154]:
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59]) 
np.hstack((heights , weights)).shape

(8,)

In [163]:
sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])

x= sales.reshape(4 , 3)
print(x.mean(axis=1))
print(x.mean(axis=1).argmax())




[117.66666667 175.          95.         212.66666667]
3


In [164]:
a = np.array([2, 3, 4])
b = np.array([[2],
              [3],
              [4]])
print(a+b)

[[4 5 6]
 [5 6 7]
 [6 7 8]]


In [166]:
arr = np.arange(1 , 21)
np.where(arr%3==0 , -1 , arr)

array([ 1,  2, -1,  4,  5, -1,  7,  8, -1, 10, 11, -1, 13, 14, -1, 16, 17,
       -1, 19, 20])

In [ ]:
arr = np.array([[ 50, 1200, 3],
                [ 80, 1500, 9],
                [ 65, 900, 5],
                [ 95, 2000, 7]])

##(x - col_min) / (col_max - col_min)

col_min = arr.min(axis=0)
col_max = arr.max(axis=0)
print(col_max)
print(col_min)
print(x-col_min/col_max-col_min)

[  95 2000    9]
[ 50 900   3]
[[  69.47368421 -765.45         94.66666667]
 [ 109.47368421 -725.45        186.66666667]
 [  37.47368421 -808.45        101.66666667]
 [ 159.47368421 -702.45        226.66666667]]


['gold' 'bronze' 'silver' '45' 'silver' 'silver' '59' 'bronze']


In [181]:
m = np.array([[10, 80, 45],
             [55, 20, 99],
             [70, 33, 12]])

p = np.where(m>50 , 0 , m).copy()
print(m)
print("")
print(p)


[[10 80 45]
 [55 20 99]
 [70 33 12]]

[[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]


In [186]:
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

print(np.vstack((s1, s2 ,s3)))
print("")
print(np.hstack((s1[:, None] , s2[: , None] , s3[:, None])))

[[12 15 11 19 14]
 [22 18 25 21 20]
 [31 35 29 33 30]]

[[12 22 31]
 [15 18 35]
 [11 25 29]
 [19 21 33]
 [14 20 30]]


In [ ]:
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

arr = np.hstack((hours[:, None] , attendance[: , None]))
print(arr)
arr.shape
column = arr.sum(axis=1)



[[ 2 55]
 [ 8 92]
 [ 5 70]
 [10 98]
 [ 3 60]
 [ 7 85]]


(6, 2)